// AUTO-GENERATED BY UpdatePartyVersion.ps1 - DO NOT MODIFY
#if UNITY_STANDALONE || UNITY_IOS || UNITY_STANDALONE_OSX || UNITY_EDITOR_OSX || UNITY_ANDROID || UNITY_GAMECORE || MICROSOFT_GAME_CORE || UNITY_STANDALONE_LINUX || UNITY_EDITOR_LINUX || UNITY_SWITCH || UNITY_PS4 || UNITY_PS5
namespace PlayFab.Party
{
    internal static class Version
    {
        public static readonly string PartyNativeVersion = "{1.10.5}PlayFab.Party.Unity.Release.(Win10,GDK,Android,Apple,Linux)_2503.13001";
        public static readonly string PartyUnityVersion = "{1.10.0-main.0}PlayFab.Party.Unity.Release.(Win10,GDK,Android,Apple,Linux)_2503.13001";
    }
}
#endif
