name: Build 😎

on:
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

jobs:
  call-shared-build:
    uses: ./.github/workflows/unity-build-reusable.yml
    with:
      do_release: false
    secrets: inherit
