name: Build ChaosBomber Executable

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-zip:
    name: Build .love File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create .love File
        run: |
          cd src/chaos_bomber
          zip -9 -r ../../chaosbomber.love .
          cd ../..

      - name: Upload .love Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chaosbomber-love
          path: chaosbomber.love

  build-windows:
    name: Build Windows Executable
    runs-on: ubuntu-latest
    needs: build-zip
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download .love Artifact
        uses: actions/download-artifact@v4
        with:
          name: chaosbomber-love
          path: .

      - name: Install Dependencies
        run: sudo apt-get update && sudo apt-get install -y zip unzip wget

      - name: Run Windows Build Script
        run: bash src/script/build_windows.sh 11.5 win64

      - name: Upload Windows Executable
        uses: actions/upload-artifact@v4
        with:
          name: chaosbomber-windows
          path: build/chaosbomber-11.5-win64.zip

  build-mac:
    name: Build macOS Application
    runs-on: macos-latest
    needs: build-zip
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download .love Artifact
        uses: actions/download-artifact@v4
        with:
          name: chaosbomber-love
          path: .

      - name: Install LÖVE
        run: brew install --cask love

      - name: Create macOS Application Bundle
        run: |
          mkdir ChaosBomber.app
          cp -R /Applications/love.app/Contents ChaosBomber.app/
          cp chaosbomber.love ChaosBomber.app/Contents/Resources/
          plutil -replace CFBundleName -string "ChaosBomber" ChaosBomber.app/Contents/Info.plist
          plutil -replace CFBundleIdentifier -string "com.yourdomain.chaosbomber" ChaosBomber.app/Contents/Info.plist
          plutil -replace CFBundleExecutable -string "love" ChaosBomber.app/Contents/Info.plist

      - name: Compress macOS Application
        run: zip -9 -r chaosbomber-mac.zip ChaosBomber.app

      - name: Upload macOS Application
        uses: actions/upload-artifact@v4
        with:
          name: chaosbomber-mac
          path: chaosbomber-mac.zip
