name: Build

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-shared-build:
    uses: ./.github/workflows/unity-build-reusable.yml
    with:
      do_release: false
    secrets: inherit
