name: Linting

on:
  pull_request:
    branches: [ main, master ]

jobs:
  luacheck:
    name: Lua Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Install Lua and Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks
          luarocks --local install luacheck
          echo "export PATH=\$HOME/.luarocks/bin:\$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Run Luacheck
        run: |
          $HOME/.luarocks/bin/luacheck . --no-color --codes --exclude-files .luacheckrc
