name: Linting

on:
  pull_request:
    branches: [ main, master ]

jobs:
  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

  luacheck:
    name: Lua Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3.1.0

      - name: Install Lua and Luacheck
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks
          luarocks install luacheck

      - name: Run Luacheck
        run: |
          luacheck . --no-color --codes --exclude-files .luacheckrc
