name: Build and Release 🚀🚀🚀

on:
  workflow_dispatch:
  push:
    branches:
      - master # temporary: run build+release on master pushes while release flow is being stabilized
    tags:
      - '*'  # Runs on any tag push

jobs:
  call-shared-build-and-release:
    uses: ./.github/workflows/unity-build-reusable.yml
    with:
      do_release: true
      release_version: ${{ github.ref_name }}
    secrets: inherit
