name: Unit Tests

on:
  pull_request:
    branches: [ main, master ]

jobs:
  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache LuaRocks Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.luarocks
          key: luarocks-${{ runner.os }}-${{ hashFiles('**/rockspec') }}
          restore-keys: |
            luarocks-${{ runner.os }}-

      - name: Install Lua and Busted
        run: |
          sudo apt-get update
          sudo apt-get install -y lua5.4 luarocks
          if [ ! -d "$HOME/.luarocks/bin" ]; then
            luarocks --local install busted
          fi
          echo "export PATH=\$HOME/.luarocks/bin:\$PATH" >> ~/.bashrc
          source ~/.bashrc

      - name: Run Unit Tests
        run: |
          LUA_PATH="./src/chaos_bomber/?.lua;./src/chaos_bomber/?/init.lua;" $HOME/.luarocks/bin/busted tests/
